[package]
name = "join_per_sample_vcfs"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
flate2 = "1.1.9"
lru = "0.16.3"
tempfile = "3"
thiserror = "2.0.18"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "gvcf_perf"
harness = false
